/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontSize: {
      oveline: ["10px", { lineHeight: "1rem", fontWeight: 600 }],
      caption: ["12px", { lineHeight: "1.25rem", fontWeight: 500 }],
      button: ["14px", { lineHeight: "1.5rem", fontWeight: 400 }],
      body2: ["14px", { lineHeight: "1.75rem", fontWeight: 600 }],
      body1: ["16px", { lineHeight: "1.75rem", fontWeight: 400 }],
      subtitle2: ["18px", { lineHeight: "2rem", fontWeight: 400 }],
      subtitle1: ["22px", { lineHeight: "2.25rem", fontWeight: 400 }],
      h6: ["24px", { lineHeight: "2.5rem", fontWeight: 600 }],
      h5: ["28px", { lineHeight: "1", fontWeight: 700 }],
      h4: ["38px", { lineHeight: "1", fontWeight: 700 }],
      h3: ["40px", { lineHeight: "1", fontWeight: 700 }],
      h2: ["48px", { lineHeight: "1", fontWeight: 700 }],
      h1: ["72px", { lineHeight: "1", fontWeight: 700 }],
    },
    extend: {
      maxWidth: {
        "7xl": "1344px",
      },
      fontFamily: {
        inter: ["Inter"],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: [
          "Inter",
          "ui-serif",
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "Times",
          "serif",
        ],
        mono: [
          "Inter",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
    },
  },
  plugins: [],
};
