/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      black: "#000000",
      gray: {
        50: "#F0F1F3",
        100: "#E0E1E7",
        200: "#C1C3CE",
        300: "#A2A5B6",
        400: "#83879D",
        500: "#646985",
        600: "#4B4F64",
        700: "#323543",
        800: "#191A21",
        900: "#0A0B0D",
      },
      primary: {
        50: "#E7F1FD",
        100: "#CDE1FB",
        200: "#9BC4F7",
        300: "#69A6F2",
        400: "#3789EE",
        500: "#056BEA",
        600: "#0450B0",
        700: "#033675",
        800: "#011B3B",
        900: "#010B17",
      },
    },
    fontSize: {
      oveline: ["10px", { lineHeight: "1rem", fontWeight: 600 }],
      caption: ["12px", { lineHeight: "1.25rem", fontWeight: 500 }],
      button: ["14px", { lineHeight: "1.5rem", fontWeight: 500 }],
      body2: ["14px", { lineHeight: "1.75rem", fontWeight: 600 }],
      body1: ["16px", { lineHeight: "1.75rem", fontWeight: 400 }],
      subtitle2: ["18px", { lineHeight: "2rem", fontWeight: 400 }],
      subtitle1: ["22px", { lineHeight: "2.25rem", fontWeight: 400 }],
      h6: ["24px", { lineHeight: "2.5rem", fontWeight: 600 }],
      h5: ["28px", { lineHeight: "1", fontWeight: 700 }],
      h4: ["38px", { lineHeight: "1", fontWeight: 700 }],
      h3: ["40px", { lineHeight: "1", fontWeight: 700 }],
      h2: ["48px", { lineHeight: "1", fontWeight: 700 }],
      h1: ["72px", { lineHeight: "1", fontWeight: 700 }],
    },
    extend: {
      maxWidth: {
        "7xl": "1344px",
      },
      fontFamily: {
        inter: ["Inter"],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: [
          "Inter",
          "ui-serif",
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "Times",
          "serif",
        ],
        mono: [
          "Inter",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
    },
  },
  plugins: [],
};
